apiVersion: v1
kind: Service
metadata:
  name: {{ include "persuasion4good.fullname" . }}-backend
  labels:
    {{- include "persuasion4good.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "persuasion4good.backend.selectorLabels" . | nindent 4 }}
